### ISSUE TITLE
clicking links shouldn't trigger the activation of the comments sidebar

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commentpress-mla#10]
When clicking on a link, CommentPress thinks I want to comment on the paragraph that contains that link. The link is still followed, but there is a delay of a few seconds while the sidebar animates.

**Comment by chriszarate** [comment]
Check in with me before tackling this; there should be a relatively simple `class`-based approach.

**Comment by christianwach** [comment]
This is fixed in CommentPress Core 3.8.8, so you should remove this Javascript to prevent adverse effects on the bubbling of other click events up the DOM.

**Comment by chriszarate** [comment]
Thanks @christianwach, will do.
