### ISSUE TITLE
Compatibility with CommentPress Core 3.8.5+

### ISSUE THREAD

**Issue by christianwach** [mlaa/commentpress-mla#16]
After @chriszarate created a PR on the main CommentPress Core repo, I took a look at your child themes to see why you're still using CommentPress Core 3.8.4 and realised that it likely to be because I merged the default theme's separate stylesheets into a single file and made the default enqueuing handle `cp_layout_css` instead of `cp_reset_css`, thus causing your child theme styles not to load.

The fix for this is simple - as is the fix for a Javascript error that I see when I [visit a comment permalink](https://dlsanthology.commons.mla.org/from-reading-to-social-computing/#comment-194065) - but I wondered what your branching policy was so that I could create PRs to bring your child theme(s) up-to-date.

**Comment by chriszarate** [comment]
We use a simplified gitflow, but this repo hasn't seen much activity in awhile. Thanks very much for pointing the way; it's an easy fix so I'll push it shortly.
