### ISSUE TITLE
create new TOC section for essays under review

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commentpress-mla#2]
1. create new page template "Section Header," identical to page
2. create new page titled "Essays Under Review," assign it the page template "Section Header"
3. in CSS, disable linking for this pages with this template
4. add new essays as pages, assigning `order` property so that they appear below section header

**Comment by JonathanReeve** [comment]
The new section is live on Ellison. Here's a screenshot:

![selection_476](https://cloud.githubusercontent.com/assets/1843676/5784252/7c7accc0-9d98-11e4-8b25-a9c44cdd255a.png)

But it turns out that disabling a link in CSS stirs up a few additional problems, since as a page, it's still accessible by clicking the "<" arrow at the top of the page, and by clicking the link itself on an outdated browser (IE < 11). One solution to might be to add badges to the pages instead: 

![selection_475](https://cloud.githubusercontent.com/assets/1843676/5784279/c779bcae-9d98-11e4-824d-215acf73e54a.png)

**Comment by JonathanReeve** [comment]
Oops, according to http://caniuse.com/#feat=pointer-events, it looks like it's not supported for links in IE 11, either.

**Comment by chriszarate** [comment]
I don't mind the badges, actually. We could run those by the appropriate folks.

**Comment by terrainsvagues** [comment]
The badges are good, but could do with some color & perhaps an additional call to action asking people to comment?

**Comment by JonathanReeve** [comment]
How about this? 

![selection_477](https://cloud.githubusercontent.com/assets/1843676/5784702/b03dcd06-9d9c-11e4-99cd-1b6170214b49.png)

I readjusted the line height and reduced the size of the badge a bit. Baby blue isn't my favorite, but "MLA Orange" looked terrible here, and that color of blue is used for the boxes on the "Welcome" page. 

Regarding a call to action, we could add another blue instructional box like the one on "Welcome" to the new essays.
