### ISSUE TITLE
scale images to container width

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commentpress-mla#3]
Images aren't scaling well to the size of the window/container: 

![selection_446](https://cloud.githubusercontent.com/assets/1843676/5147586/9bef25d2-7184-11e4-96ad-0d424f045ded.png)

**Comment by JonathanReeve** [comment]
Fixed this on the digital-pedagogy branch in 47602ed. I'll merge this into `develop` if I can do some testing on LSDA.

**Comment by christianwach** [comment]
This is fixed [upstream](https://github.com/christianwach/commentpress-core/commit/0c4438d24545ca2a985749ce704154b044848f27) and will be in the 3.8.8 release.
