### ISSUE TITLE
active state of volume title link is a spooky dark green

### ISSUE THREAD

**Issue by JonathanReeve** [mlaa/commentpress-mla#5]
Clicking on "Digital Pedagogy in the Humanities" at the top of the screen causes that link to become dark green, which is the not the prettiest color in this color scheme.

**Comment by christianwach** [comment]
You're actually seeing the `:focus` state of the link which is there for keyboard accessibility. I have overhauled keyboard accessibility in CommentPress Core 3.8.8 and you'll see the title underlined instead.
